// _study/onnote/vue_js_typescript/vue-typescript-tutorial/4-todo-app-vuex/src/components/TodoFilter.vue
<template>
  <div>
    <input
      type="radio"
      v-bind:checked="filter === 'ALL'"
      v-on:change="setFilter('ALL')"
    />전체
    <input
      type="radio"
      v-bind:checked="filter === 'NOTDONE'"
      v-on:change="setFilter('NOTDONE')"
    />미완료
    <input
      type="radio"
      v-bind:checked="filter === 'DONE'"
      v-on:change="setFilter('DONE')"
    />완료
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { State, Mutation } from 'vuex-class';
import { SET_FILTER } from '../store/mutation-types';

@Component
export default class TodoFilter extends Vue {
  // 필터링 유형 데이터 맵핑
  @State filter!: string;

  // 필터링 유형을 변경하는 메서드
  @Mutation(SET_FILTER) readonly setFilter: any;
}
</script>

// _study/onnote/react/react-tutorial/4-todo-app-redux/src/components/TodoFilter.js
import React from 'react';
import styles from '../Todo.module.css';

// filter, onChangeFilter props로 수신
const TodoFilter = ({ filter, onChangeFilter }) => {
  // 필터링 유형 변경 이벤트 처리 함수
  const handleFilter = (e) => onChangeFilter(e.target.value);

  return (
    <div className={styles.filter}>
      <input type="radio" value="ALL" checked={filter === 'ALL'} onChange={handleFilter} />전체{' '}
      <input type="radio" value="NOTDONE" checked={filter === 'NOTDONE'} onChange={handleFilter} />미완료{' '}
      <input type="radio" value="DONE" checked={filter === 'DONE'} onChange={handleFilter} />완료
    </div>
  );
};

export default TodoFilter;
