// _study/onnote/react_typescript/chap06_CRUD 게시판/4-라우터 정의/src/components/BoardModifyForm.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import styles from '../Board.module.css';

function BoardModifyForm() {
  return (
    <div className={styles.centered}>
      <h2>게시판 수정</h2>
      <form>
        <table>
          <tbody>
            <tr>
              <td>번호</td>
              <td><input type="text" value="100" disabled /></td>
            </tr>
            <tr>
              <td>등록일시</td>
              <td><input type="text" value="2022-02-23" disabled /></td>
            </tr>
            <tr>
              <td>작성자</td>
              <td><input type="text" value="홍길동" disabled /></td>
            </tr>
            <tr>
              <td>제목</td>
              <td><input type="text" /></td>
            </tr>
            <tr>
              <td>내용</td>
              <td><textarea rows={5}></textarea></td>
            </tr>
          </tbody>
        </table>

        <div className={styles.align_centered}>
          <button type="submit">수정</button>
          <Link to={'/read/100'}>취소</Link>
        </div>
      </form>
    </div>
  );
}

export default BoardModifyForm;

// _study/onnote/vue_js/chap05_CRUD 게시판/10_게시글 수정/src/components/BoardModifyForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>번호</td>
        <td><input type="text" :value="board.boardNo" disabled /></td>
      </tr>
      <tr>
        <td>등록일시</td>
        <td><input type="text" :value="board.regDate" disabled /></td>
      </tr>
      <tr>
        <td>작성자</td>
        <td><input type="text" :value="board.writer" disabled /></td>
      </tr>
      <tr>
        <td>제목</td>
        <td><input type="text" v-model="title" /></td>
      </tr>
      <tr>
        <td>내용</td>
        <td><textarea v-model="content" rows="5"></textarea></td>
      </tr>
    </table>

    <div>
      <button type="submit">수정</button>
      <router-link
        :to="{ name: 'BoardReadPage', params: { boardNo: board.boardNo.toString() } }"
      >취소</router-link>
    </div>
  </form>
</template>

<script>
export default {
  name: 'BoardModifyForm',
  props: {
    board: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      title: '',
      content: '',
    };
  },
  methods: {
    onSubmit() {
      const { title, content } = this;
      this.$emit('submit', { title, content });
    },
  },
  created() {
    this.title = this.board.title;
    this.content = this.board.content;
  },
};
</script>
