// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/4_이벤트 처리 함수 호출/components/ItemInput.js
import React from 'react';

const ItemInput = ({ items, onChangePrice }) => {
  // 삭제
  //const handleChange = (e) => {
  //  console.log('name:', e.target.name);
  //  console.log('value:', e.target.value);
  //  onChangePrice(e.target.name, e.target.value);
  //};

  return (
    <ul>
      {/* 이벤트 처리 함수(handleChange) 지정 */}
      {items.map((item) => {
        return (
          <li key={item.name}>
            {item.name}의 가격:{' '}
            <input
              type="text"
              name={item.name}
              value={item.price}
              onChange={(e) => onChangePrice(item.name, e.target.value)}
            />
          </li>
        );
      })}
    </ul>
  );
};

export default ItemInput;

// _study/onnote/vue_js_3/chap03_Vue_js_3 기본/3-18_이벤트 전달/1-컴포지션 API 방식/src/components/ItemInput.vue
<template>
  <div>
    {{ item.name }}의 가격:
    <input type="text" v-on:input="changePrice" v-bind:value="item.price" />
  </div>
</template>

<script>
export default {
  name: 'ItemInput',
  props: ['item', 'itemIndex'],
  emits: ['change-price'], // 전송할 이벤트 정의
  setup(props, context) {
    const changePrice = (event) => {
      const newPrice = event.target.value;
      // 이벤트 발생
      context.emit('change-price', newPrice, props.itemIndex);
    };

    return {
      changePrice,
    };
  },
};
</script>
