// _study/zerocho/vue_js-webgame/07-TicTacToe-EventBus/TableComponent.vue
<template>
  <table>
    <tr-component
      v-for="(rowData, index) in tableData"
      :key="index"
      :row-data="rowData"
      :row-index="index"
    ></tr-component>
  </table>
</template>

<script>
import TrComponent from './TrComponent.vue';

export default {
  props: {
    tableData: Array
  },
  components: { TrComponent }
};
</script>

// _study/zerocho/react/08-TicTacToe/Table.jsx
import React from 'react';
import Tr from './Tr';

const Table = ({ tableData, dispatch }) => {
  return (
    <table>
      {Array(tableData.length).fill().map((tr, i) =>(
        <Tr key ={i} dispatch={dispatch} rowIndex={i} rowData={tableData[i]} />))}
    </table>
  );
};

export default Table;
