// _study/zerocho/vue_js-webgame/07-TicTacToe/TdComponent.vue
<template>
  <td @click="onClickTd">{{ cellData }}</td>
</template>

<script>
export default {
  props: {
    cellData: String,
    rowIndex: Number,
    cellIndex: Number
  },
  methods: {
    onClickTd() {
      if (this.cellData) return;

      const rootData = this.$root.$data;
      //console.log(rootData);
      this.$set(
        rootData.tableData[this.rowIndex],
        this.cellIndex,
        rootData.turn
      );

      let win = false;
      if (
        rootData.tableData[this.rowIndex][0] === rootData.turn &&
        rootData.tableData[this.rowIndex][1] === rootData.turn &&
        rootData.tableData[this.rowIndex][2] === rootData.turn
      ) {
        win = true;
      }
      if (
        rootData.tableData[0][this.cellIndex] === rootData.turn &&
        rootData.tableData[1][this.cellIndex] === rootData.turn &&
        rootData.tableData[2][this.cellIndex] === rootData.turn
      ) {
        win = true;
      }
      if (
        rootData.tableData[0][0] === rootData.turn &&
        rootData.tableData[1][1] === rootData.turn &&
        rootData.tableData[2][2] === rootData.turn
      ) {
        win = true;
      }
      if (
        rootData.tableData[0][2] === rootData.turn &&
        rootData.tableData[1][1] === rootData.turn &&
        rootData.tableData[2][0] === rootData.turn
      ) {
        win = true;
      }

      if (win) { // 이긴 경우: 3줄 달성
        rootData.winner = rootData.turn;
        rootData.turn = 'O';
        //rootData.tableData = [
        //  ['', '', ''],
        //  ['', '', ''],
        //  ['', '', '']
        //];
      } else { // 무승부
        let all = true; // all이 true면 무승부라는 뜻
        rootData.tableData.forEach(row => { // 무승부 검사
          row.forEach(cell => {
            if (!cell) {
              all = false;
            }
          });
        });
        if (all) { // 무승부
          rootData.winner = '';
          rootData.turn = 'O';
          //rootData.tableData = [
          //  ['', '', ''],
          //  ['', '', ''],
          //  ['', '', '']
          //];
        } else {
          rootData.turn = rootData.turn === 'O' ? 'X' : 'O';
        }
      }
    }
  }
};
</script>

// _study/zerocho/react/08-TicTacToe/Td.jsx
import React, { useCallback, memo } from 'react';
import { CLICK_CELL } from './TicTacToe';

const Td = ({ rowIndex, cellIndex, dispatch, cellData }) => {
  const onClickTd = useCallback(() => {
    if (cellData) {
      console.log(rowIndex, cellIndex);
      return;
    }
    dispatch({ type: CLICK_CELL, row: rowIndex, cell: cellIndex });
  }, [cellData]);

  return (
    <td onClick={onClickTd}>{cellData}</td>
  );
};

export default Td;
