// _study/onnote/react/chap09_실전 프로젝트/16_회원 관리/src/components/member/MemberModifyForm.js
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { fetchJobCodeList } from 'lib/api';

import M from 'materialize-css';

const MemberModifyForm = ({ member, isLoading, onModify }) => {
  const [jobCodes, setJobCodes] = useState([]);

  const [userName, setUserName] = useState('');
  const [job, setJob] = useState('');

  const [auth1, setAuth1] = useState('');
  const [auth2, setAuth2] = useState('');
  const [auth3, setAuth3] = useState('');

  // 사용자명 값의 변경을 처리하는 함수
  const handleChangeUserName = (e) => {
    setUserName(e.target.value);
  };
  // 직업의 변경을 처리하는 함수
  const handleChangeJob = (e) => {
    setJob(e.target.value);
  };
  // 사용자 권한의 변경을 처리하는 함수
  const handleChangeAuth1 = (e) => {
    setAuth1(e.target.value);
  };
  const handleChangeAuth2 = (e) => {
    setAuth2(e.target.value);
  };
  const handleChangeAuth3 = (e) => {
    setAuth3(e.target.value);
  };

  // 폼 submit 이벤트 처리
  const handleSubmit = (e) => {
    e.preventDefault();
    const userNo = member.userNo;
    const userObject = {
      userId: member.userId,
      userPw: member.userPw,
      userName: userName,
      job: job,
      authList: [
        {
          userNo,
          auth: auth1,
        },
        {
          userNo,
          auth: auth2,
        },
        {
          userNo,
          auth: auth3,
        },
      ],
    };
    onModify(member.userNo, userObject);
  };

  // 직업코드 목록을 가져옴
  const getJobCodeList = async () => {
    try {
      const response = await fetchJobCodeList();
      setJobCodes(response.data);
    } catch (err) {
      throw err;
    }
  };

  useEffect(() => {
    M.AutoInit(); // materialize select 태그 사용
  });

  // 마운팅될 때 직업 코드 목록을 가져옴
  useEffect(() => {
    getJobCodeList();
  }, []);

  // 마운트될 때 기존의 사용자명, 직업코드, 권한을 가져옴
  useEffect(() => {
    if (member) {
      setUserName(member.userName);
      setJob(member.job);
      setAuth1(member.authList[0] && member.authList[0].auth);
      setAuth2(member.authList[1] && member.authList[1].auth);
      setAuth3(member.authList[2] && member.authList[2].auth);
    }
  }, [member]);

  // 회원 수정 폼 화면 표시
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '40px' }}>회원 수정</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && member && (
        <div className="row">
          <form onSubmit={handleSubmit} className="col s12">
            <div className="row">
              <div className="input-field col s12">
                <input type="text" id="userNo" value={member.userNo} disabled />
                <label className="active" htmlFor="userNo">번호</label>
              </div>
              <div className="input-field col s12">
                <input type="text" id="userId" value={member.userId} disabled />
                <label className="active" htmlFor="userId">아이디</label>
              </div>
              <div className="input-field col s12">
                <input
                  type="text"
                  id="userName"
                  value={userName}
                  onChange={handleChangeUserName}
                  required
                />
                <label className="active" htmlFor="userName">사용자명</label>
              </div>
              <div className="input-field col s12">
                <select id="jobCode" value={job} onChange={handleChangeJob}>
                  {jobCodes.map((jobCode) => (
                    <option value={jobCode.value} key={jobCode.value}>
                      {jobCode.label}
                    </option>
                  ))}
                </select>
                <label htmlFor="jobCode">직업</label>
              </div>
            </div>
            <div className="row">
              <div className="input-field col s12">
                <select id="auth1" value={auth1} onChange={handleChangeAuth1}>
                  <option value="">--- 선택해 주세요 ---</option>
                  <option value="ROLE_USER">사용자</option>
                  <option value="ROLE_MEMBER">회원</option>
                  <option value="ROLE_ADMIN">관리자</option>
                </select>
                <label htmlFor="auth1">권한 - 1</label>
              </div>
              <div className="input-field col s12">
                <select id="auth2" value={auth2} onChange={handleChangeAuth2}>
                  <option value="">--- 선택해 주세요 ---</option>
                  <option value="ROLE_USER">사용자</option>
                  <option value="ROLE_MEMBER">회원</option>
                  <option value="ROLE_ADMIN">관리자</option>
                </select>
                <label htmlFor="auth2">권한 - 2</label>
              </div>
              <div className="input-field col s12">
                <select id="auth3" value={auth3} onChange={handleChangeAuth3}>
                  <option value="">--- 선택해 주세요 ---</option>
                  <option value="ROLE_USER">사용자</option>
                  <option value="ROLE_MEMBER">회원</option>
                  <option value="ROLE_ADMIN">관리자</option>
                </select>
                <label htmlFor="auth3">권한 - 3</label>
              </div>
            </div>
            <br />
            <Link to={`/member/read/${member.userNo}`} className="waves-effect waves-light btn">취소</Link>{' '}
            <button type="submit" className="waves-effect waves-light btn blue">완료</button>
          </form>
        </div>
      )}
    </div>
  );
};

export default MemberModifyForm;

// _study/onnote/vue_js/chap07_실전 프로젝트/16_회원 관리/src/components/member/MemberModifyForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>번호</td>
        <td><input type="text" :value="member.userNo" disabled></td>
      </tr>
      <tr>
        <td>아이디</td>
        <td><input type="text" :value="member.userId" disabled></td>
      </tr>
      <tr>
        <td>사용자명</td>
        <td><input type="text" v-model="userName"></td>
      </tr>
      <tr>
        <td>직업</td>
        <td>
          <select v-model="job" :value="member.job">
            <option v-for="jobCode in jobCodes" :value="jobCode.value" :key="jobCode.value">
              {{ jobCode.label }}
            </option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 1</td>
        <td>
          <select v-model="auth1">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 2</td>
        <td>
          <select v-model="auth2">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 3</td>
        <td>
          <select v-model="auth3">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
    </table>
    <div>
      <button type="submit">수정</button>
      <router-link :to="{ name: 'MemberReadPage', params: { userNo: member.userNo } }">취소</router-link>
    </div>
  </form>
</template>

<script>
export default {
  name: 'MemberModifyForm',
  props: {
    member: {
      type: Object,
      required: true,
    },
    jobCodes: {
      type: Array,
    }
  },
  data() {
    return {
      userId: '',
      userPw: '',
      userName: '',
      job: '',
      auth1: '',
      auth2: '',
      auth3: '',
    };
  },
  methods: {
    onSubmit() {
      const { userId, userPw, userName, job, auth1, auth2, auth3 } = this;
      const userNo = this.member.userNo;

      const userObject = {
        userId,
        userPw,
        userName,
        job,
        authList: [
          {
            userNo: userNo,
            auth: auth1,
          },
          {
            userNo: userNo,
            auth: auth2,
          },
          {
            userNo: userNo,
            auth: auth3,
          },
        ],
      };

      this.$emit('submit', userObject);
    },
  },
  created() {
    this.userId = this.member.userId;
    this.userPw = this.member.userPw;
    this.userName = this.member.userName;
    this.job = this.member.job;

    if (this.member.authList[0]) {
      this.auth1 = this.member.authList[0].auth;
    }
    if (this.member.authList[1]) {
      this.auth1 = this.member.authList[1].auth;
    }
    if (this.member.authList[2]) {
      this.auth1 = this.member.authList[2].auth;
    }
  }
};
</script>
