// _study/onnote/react/chap09_실전 프로젝트/16_회원 관리/src/components/member/MemberRead.js
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { fetchJobCodeList } from 'lib/api';

import M from 'materialize-css';

const MemberRead = ({ member, userNo, isLoading, onRemove }) => {
  // 컴포넌트 상태 설정
  const [jobCodes, setJobCodes] = useState([]);

  // 직업코드 목록을 가져옴
  const getJobCodeList = async () => {
    try {
      const response = await fetchJobCodeList();
      setJobCodes(response.data);
    } catch (err) {
      throw err;
    }
  };

  useEffect(() => {
    M.AutoInit(); // materialize select 태그 사용
  });

  // 마운팅될 때 직업 코드 목록을 가져옴
  useEffect(() => {
    getJobCodeList();
  }, []);

  // 회원 상세보기 화면 표시
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '40px' }}>회원 상세보기</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && member && (
        <div className="row">
          <div className="row">
            <div className="input-field col s12">
              <input type="text" id="userNo" value={member.userNo} disabled />
              <label className="active" htmlFor="userNo">번호</label>
            </div>
            <div className="input-field col s12">
              <input type="text" id="userId" value={member.userId} readOnly />
              <label className="active" htmlFor="userId">아이디</label>
            </div>
            <div className="input-field col s12">
              <input type="text" id="userName" value={member.userName} readOnly />
              <label className="active" htmlFor="userName">사용자명</label>
            </div>
            <div className="input-field col s12">
              <select id="jobCode" value={member.job} disabled>
                {jobCodes.map((jobCode) => (
                  <option value={jobCode.value} key={jobCode.value}>
                    {jobCode.label}
                  </option>
                ))}
              </select>
              <label htmlFor="jobCode">직업</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <select id="auth1" value={member.authList[0] && member.authList[0].auth} disabled>
                <option value="">--- 선택해 주세요 ---</option>
                <option value="ROLE_USER">사용자</option>
                <option value="ROLE_MEMBER">회원</option>
                <option value="ROLE_ADMIN">관리자</option>
              </select>
              <label htmlFor="auth1">권한 - 1</label>
            </div>
            <div className="input-field col s12">
              <select id="auth2" value={member.authList[1] && member.authList[1].auth} disabled>
                <option value="">--- 선택해 주세요 ---</option>
                <option value="ROLE_USER">사용자</option>
                <option value="ROLE_MEMBER">회원</option>
                <option value="ROLE_ADMIN">관리자</option>
              </select>
              <label htmlFor="auth2">권한 - 2</label>
            </div>
            <div className="input-field col s12">
              <select id="auth3" value={member.authList[2] && member.authList[2].auth} disabled>
                <option value="">--- 선택해 주세요 ---</option>
                <option value="ROLE_USER">사용자</option>
                <option value="ROLE_MEMBER">회원</option>
                <option value="ROLE_ADMIN">관리자</option>
              </select>
              <label htmlFor="auth3">권한 - 3</label>
            </div>
          </div>
          <br />
          <Link to="/member" className="waves-effect waves-light btn">
            회원 목록
          </Link>{' '}
          <Link to={`/member/edit/${userNo}`} className="waves-effect waves-light btn blue">수정</Link>
          <button onClick={onRemove} className="waves-effect waves-light btn red right">삭제</button>
        </div>
      )}
    </div>
  );
};

export default MemberRead;

// _study/onnote/vue_js/chap07_실전 프로젝트/16_회원 관리/src/components/member/MemberRead.vue
<template>
 <div>
    <table>
      <tr>
        <td>번호</td>
        <td><input type="text" :value="member.userNo" readonly></td>
      </tr>
      <tr>
        <td>아이디</td>
        <td><input type="text" :value="member.userId" readonly></td>
      </tr>
      <tr>
        <td>사용자명</td>
        <td><input type="text" :value="member.userName" readonly></td>
      </tr>
      <tr>
        <td>직업</td>
        <td>
          <select v-model="member.job" disabled>
            <option v-for="jobCode in jobCodes" :value="jobCode.value" :key="jobCode.value">
              {{ jobCode.label }}
            </option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 1</td>
        <td>
          <select :value="auth1">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 2</td>
        <td>
          <select :value="auth2">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>권한 - 3</td>
        <td>
          <select :value="auth3">
            <option value="" selected="selected">=== 선택해 주세요 ===</option>
            <option value="ROLE_USER">사용자</option>
            <option value="ROLE_MEMBER">회원</option>
            <option value="ROLE_ADMIN">관리자</option>
          </select>
        </td>
      </tr>
    </table>
    <div>
      <button type="submit">등록</button>
      <router-link :to="{ name: 'MemberListPage' }">목록</router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MemberRead',
  props: {
    member: {
      type: Object,
      required: true,
    },
    jobCodes: {
      type: Array,
    },
  },
  computed: {
    auth1() {
      if (this.member.authList[0]) {
        return this.member.authList[0].auth;
      }
      return '';
    },
    auth2() {
      if (this.member.authList[1]) {
        return this.member.authList[1].auth;
      }
      return '';
    },
    auth3() {
      if (this.member.authList[2]) {
        return this.member.authList[2].auth;
      }
      return '';
    },
  }
};
</script>
