// _study/onnote/react/react-tutorial/4-todo-app-redux/src/components/TodoFilter.js
import React from 'react';
import styles from '../Todo.module.css';

// filter, onChangeFilter props로 수신
const TodoFilter = ({ filter, onChangeFilter }) => {
  // 필터링 유형 변경 이벤트 처리 함수
  const handleFilter = (e) => onChangeFilter(e.target.value);

  return (
    <div className={styles.filter}>
      <input type="radio" value="ALL" checked={filter === 'ALL'} onChange={handleFilter} />전체{' '}
      <input type="radio" value="NOTDONE" checked={filter === 'NOTDONE'} onChange={handleFilter} />미완료{' '}
      <input type="radio" value="DONE" checked={filter === 'DONE'} onChange={handleFilter} />완료
    </div>
  );
};

export default TodoFilter;

// _study/onnote/vue_js_3/chap04_Todo 애플리케이션/15_검색 필터링 컴포넌트 정의/src/components/TodoFilter.vue
<template>
  <div>
    <input
      type="radio"
      v-bind:checked="filter === 'ALL'"
      v-on:change="setFilter('ALL')"
    />전체
    <input
      type="radio"
      v-bind:checked="filter === 'NOTDONE'"
      v-on:change="setFilter('NOTDONE')"
    />미완료
    <input
      type="radio"
      v-bind:checked="filter === 'DONE'"
      v-on:change="setFilter('DONE')"
    />완료
  </div>
</template>

<script>
import { computed } from 'vue';
import { useStore } from 'vuex';

export default {
  name: 'TodoFilter',
  setup() {
    const store = useStore();

    // 필터링 유형 데이터 computed 속성 맵핑
    const filter = computed(() => store.state.filter);

    // 필터링 유형 설정 메서드
    const setFilter = (filter) => {
      store.dispatch('setFilter', filter);
    };

    return {
      filter,
      setFilter,
    };
  },
};
</script>
