// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/4_이벤트 처리 함수 호출/components/ItemInput.js
import React from 'react';

const ItemInput = ({ items, onChangePrice }) => {
  // 삭제
  //const handleChange = (e) => {
  //  console.log('name:', e.target.name);
  //  console.log('value:', e.target.value);
  //  onChangePrice(e.target.name, e.target.value);
  //};

  return (
    <ul>
      {/* 이벤트 처리 함수(handleChange) 지정 */}
      {items.map((item) => {
        return (
          <li key={item.name}>
            {item.name}의 가격:{' '}
            <input
              type="text"
              name={item.name}
              value={item.price}
              onChange={(e) => onChangePrice(item.name, e.target.value)}
            />
          </li>
        );
      })}
    </ul>
  );
};

export default ItemInput;

// _study/onnote/vue_js/chap03_Vue_js 기본/3-17_싱글 파일 컴포넌트/src/components/ItemInput.vue
<template>
  <div>
    {{ itemName }}의 가격:
    <input type="text" v-on:input="changePrice" v-bind:value="itemPrice" />
  </div>
</template>

<script>
export default {
  name: 'item-input',
  props: [
    'itemName',
    'itemPrice',
    'itemIndex'
  ],
  methods: {
    // 하위에서 상위컴포넌트로 이벤트 전달
    changePrice(event) {
      const newPrice = event.target.value;
      console.log('newPrice:', newPrice);
      // change-price 이벤트 발생
      this.$emit('change-price', newPrice, this.itemIndex);
    }
  }
};
</script>
