// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/5_이벤트 처리 함수 호출/components/ItemInput.js
import React from 'react';

const ItemInput = ({ items, onChangePrice }) => {
  const handleChange = (e) => {
    // 데이터 세트(dataset)로 값 획득
    const selectedName = e.target.dataset.itemName;

    console.log('name', selectedName);
    console.log('value', e.target.value);

    // 부모 컴포넌트 함수 호출
    onChangePrice(selectedName, e.target.value);
  };

  return (
    <ul>
      {/* 데이터 세트(dataset)로 값 전달 */}
      {items.map((item) => {
        return (
          <li key={item.name}>
            {item.name}의 가격:{' '}
            <input
              type="text"
              data-item-name={item.name}
              value={item.price}
              onChange={handleChange}
            />
          </li>
        );
      })}
    </ul>
  );
};

export default ItemInput;

// _study/onnote/vue_js/chap03_Vue_js 기본/3-17_싱글 파일 컴포넌트/src/components/ItemInput.vue
<template>
  <div>
    {{ itemName }}의 가격:
    <input type="text" v-on:input="changePrice" v-bind:value="itemPrice" />
  </div>
</template>

<script>
export default {
  name: 'item-input',
  props: [
    'itemName',
    'itemPrice',
    'itemIndex'
  ],
  methods: {
    // 하위에서 상위컴포넌트로 이벤트 전달
    changePrice(event) {
      const newPrice = event.target.value;
      console.log('newPrice:', newPrice);
      // change-price 이벤트 발생
      this.$emit('change-price', newPrice, this.itemIndex);
    }
  }
};
</script>
