// _study/zerocho/vue_js-nodebird/front/pages/index.vue
<template>
  <v-container>
    <post-form v-if="me" />
    <div>
      <post-card v-for="p in mainPosts" v-bind:key="p.id" v-bind:post="p" />
    </div>
  </v-container>
</template>

<script>
import PostForm from '~/components/PostForm';
import PostCard from '~/components/PostCard';

export default {
  components: {
    PostForm,
    PostCard
  },
  data() {
    return {
      name: 'Nuxt.js'
    };
  },
  computed: {
    me() {
      return this.$store.state.users.me;
    },
    mainPosts() {
      return this.$store.state.posts.mainPosts;
    }
  }
};
</script>

<style>

</style>

// _study/zerocho/react-nodebird/Part02_Redux 연동하기/6-더미데이터와 포스트폼 만들기/pages/index.js
import React from 'react';
import { useSelector } from 'react-redux';
import Head from 'next/head';

import AppLayout from '../components/AppLayout';
import PostForm from '../components/PostForm';
import PostCard from '../components/PostCard';

const Home = () => {
  const { isLoggedIn } = useSelector((state) => state.user);
  const { mainPosts } = useSelector((state) => state.post);

  return (
    <AppLayout>
      <Head>
        <title>NodeBird</title>
      </Head>
      {isLoggedIn && <PostForm />}
      {mainPosts.map((post) => <PostCard key={post.id} post={post} />)}
    </AppLayout>
  );
};

export default Home;
