// _study/onnote/react/react-tutorial/9-image-shop/src/components/common/MainHeader.js
import React from 'react';
import { Link } from 'react-router-dom';

const MainHeader = ({ isAuthorized, userInfo, onLogout }) => {
  return (
    <div align="right">
      {isAuthorized && userInfo && (
        <div>
          <span>{userInfo.userName}님 환영합니다.</span>{' '}
          {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
          <a onClick={onLogout} style={{ cursor: 'pointer', marginRight: 10 }}>로그아웃</a>
        </div>
      )}
      {!isAuthorized && !userInfo && (
        <Link to='/signin' style={{ marginRight: 10 }}>로그인</Link>
      )}
    </div>
  );
}

export default MainHeader;

// _study/onnote/vue_js/chap07_실전 프로젝트/10_로그인 여부 확인/src/components/common/MainHeader.vue
<template>
  <div align="right">
    <div v-if="isAuthorized">
      <span>{{ userInfo.userName }}님 환영합니다.</span>
    </div>
    <div v-else>
      <router-link :to="{ name: 'Signin' }">로그인</router-link>
    </div>
  </div>
</template>

<script>
import { mapState, mapGetters } from 'vuex';

export default {
  name: 'MainHeader',
  computed: {
    ...mapState(['userInfo']),
    ...mapGetters(['isAuthorized', 'isAdmin']),
  },
};
</script>
