// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/2_컴포넌트 통신/1-src/components/ItemMain.js
import React, { useState, useMemo } from 'react';
import ItemList from './ItemList';

const ItemMain = () => {
  const itemDataArray = [
    {
      name: 'CPU',
      price: 462984,
      quantity: 1,
    },
    {
      name: '메인보드',
      price: 112053,
      quantity: 1,
    },
    {
      name: '메모리',
      price: 79608,
      quantity: 2,
    },
  ];

  const [items, setItems] = useState(itemDataArray);

  const calcTotalPrice = (items) => {
    return items.reduce(function (sum, item) {
      return sum + item.price * item.quantity;
    }, 0);
  };

  const totalPrice = useMemo(() => {
    return calcTotalPrice(items);
  }, [items]);

  return (
    <div>
      {/* items, totalPrice 속성(props) 값 지정 */}
      <ItemList items={items} totalPrice={totalPrice} />
    </div>
  );
};

export default ItemMain;

// _study/onnote/vue_js_3/vue3-tutorial/3-vue_js_3/src/ItemMain.vue
<template>
  <h2>Vue 컴포넌트 (컴포넌트 정의)</h2>
  <ul>
    <li v-for="item in items" v-bind:key="item.name">
      {{ item.name }}의 가격:
      <input type="text" v-on:input="item.price = $event.target.value" v-bind:value="item.price" />
    </li>
  </ul>
  <hr />
  <!-- 상품 목록 컴포넌트(ItemList) 등록 -->
  <item-list v-bind:items="items"></item-list>
</template>

<script>
import { ref } from 'vue';
import ItemList from './components/ItemList.vue'; // 지역 컴포넌트 임포트

export default {
  // 지역 컴포넌트 등록
  components: {
    ItemList,
  },
  setup() {
    const items = ref([
      {
        name: 'CPU',
        price: 462984,
        quantity: 1,
      },
      {
        name: '메인보드',
        price: 112053,
        quantity: 1,
      },
      {
        name: '메모리',
        price: 112053,
        quantity: 2,
      },
    ]);

    return {
      items,
    };
  },
};
</script>
