// _study/onnote/vue_js/vue-tutorial/7-image-shop/src/components/notice/NoticeList.vue
<template>
  <div>
    <table>
      <tr>
        <th align="center" width="80">번호</th>
        <th align="center" width="320">제목</th>
        <th align="center" width="180">등록일시</th>
      </tr>
      <tr v-if="!notices || (Array.isArray(notices) && notices.length === 0)">
        <td colspan="4">List is empty.</td>
      </tr>
      <tr v-else v-for="notice in notices" :key="notice.noticeNo">
        <td align="center">{{ notice.noticeNo }}</td>
        <td align="left">
          <router-link
            :to="{ name: 'NoticeReadPage', params: { noticeNo: notice.noticeNo.toString() } }"
          >{{ notice.title }}</router-link>
        </td>
        <td align="center">{{ notice.regDate }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'NoticeList',
  props: {
    notices: {
      type: Array,
    },
  },
};
</script>

<style scoped>
table {
  border-top: 1px solid lightgray;
  border-collapse: collapse;
}
th, td {
  border-bottom: 1px solid lightgray;
  padding: 10px;
}
</style>

// _study/onnote/react/chap09_실전 프로젝트/18_공지사항/src/components/notice/NoticeList.js
import React from 'react';
import { Link } from 'react-router-dom';

// 부모 컴포넌트에서 컴포넌트 속성으로 수신
const NoticeList = ({ notices, isAdmin, isLoading }) => {
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '30px' }}>공지사항 목록</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && notices && (
        <>
          <table>
            <thead>
              <tr>
                <th style={{ width: 80, textAlign: 'center' }}>번호</th>
                <th style={{ width: 320, textAlign: 'center' }}>제목</th>
                <th style={{ width: 180, textAlign: 'center' }}>등록일시</th>
              </tr>
            </thead>
            <tbody>
              {!notices.length && (
                <tr>
                  <td></td>
                  <td colSpan="3">
                    등록된 게시물이 없습니다.
                  </td>
                </tr>
              )}
              {!!notices.length && notices.map((notice) => (
                <tr key={notice.noticeNo}>
                  <td style={{ textAlign: 'center' }}>{notice.noticeNo}</td>
                  <td style={{ textAlign: 'left', paddingLeft: 60 }}><Link to={`/notice/read/${notice.noticeNo}`}>{notice.title}</Link></td>
                  <td style={{ textAlign: 'center' }}>{notice.regDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {isAdmin && (
            <>
              <br />
              <Link to="/notice/create" className="waves-effect waves-light btn blue">새로운 공지 작성</Link>
            </>
          )}
        </>
      )}
    </div>
  );
};

export default NoticeList;
