// _study/onnote/react/chap05_CRUD 게시판/8_게시글 목록/src/components/BoardList.js
import React from 'react';
import { Link } from 'react-router-dom';
import styles from '../Board.module.css';

// 부모 컴포넌트에서 컴포넌트 속성으로 수신
function BoardList({ boards, isLoading }) {
  return (
    <div className={styles.centered}>
      <h2>게시판 목록</h2>
      {isLoading && 'Loading...'}
      {!isLoading && boards && (
        <>
          <Link to="/create">새로만들기</Link>
          <table className={styles.board_table}>
            <thead>
              <tr>
                <th className={styles.board_no}>번호</th>
                <th className={styles.board_title}>제목</th>
                <th className={styles.board_writer}>작성자</th>
                <th className={styles.board_date}>등록일시</th>
              </tr>
            </thead>
            <tbody>
              {!boards.length && (
                <tr>
                  <td colSpan="4">List is empty.</td>
                </tr>
              )}
              {!!boards.length && boards.map((board) => (
                <tr key={board.boardNo}>
                  <td align="center">{board.boardNo}</td>
                  <td align="left"><Link to={`/read/${board.boardNo}`}>{board.title}</Link></td>
                  <td align="center">{board.writer}</td>
                  <td align="center">{board.regDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
}

export default BoardList;

// _study/onnote/vue_js/chap05_CRUD 게시판/7_게시글 목록/src/components/BoardList.vue
<template>
  <div>
    <table border="1">
      <tr>
        <th align="center" width="80">번호</th>
        <th align="center" width="320">제목</th>
        <th align="center" width="100">작성자</th>
        <th align="center" width="180">등록일시</th>
      </tr>
      <tr v-if="boards || (Array.isArray(boards) && boards.length === 0)">
        <td colspan="4">List is empty.</td>
      </tr>
      <tr v-else v-for="board in boards" :key="board.boardNo">
        <td align="center">{{ board.boardNo }}</td>
        <td align="left">
          <router-link
            :to="{ name: 'BoardReadPage', params: { boardNo: board.boardNo.toString() } }"
          >{{ board.title }}</router-link>
        </td>
        <td align="center">{{ board.writer }}</td>
        <td align="center">{{ board.regDate }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'BoardList',
  props: {
    boards: {
      type: Array,
    },
  },
};
</script>
