// _study/onnote/vue_js/vue-tutorial/6-file-board-materialize/src/components/ItemModifyForm.vue
<template>
  <div class="row">
  <form @submit.prevent="onSubmit" class="col s12">
    <div class="row">
      <div class="input-field col s5">
        <!--<input type="text" id="itemId" :value="item.itemId" disabled />-->
        <div class="item" style="color: darkgray">{{ item.itemId }}</div>
        <label class="active" for="itemId">상품번호</label>
      </div>
      <div class="input-field col s7">
        <input type="text" id="price" v-model="price" />
        <label class="active" for="price">상품가격 (원)</label>
      </div>
      <div class="input-field col s12">
        <input type="text" id="itemName" v-model="itemName" required />
        <label class="active" for="itemName">상품명</label>
      </div>
    </div>

    <div class="row">
      <div class="file-field input-field col s12">
        <div class="btn">
          <span>파일선택</span>
          <input
            type="file"
            @change="handleFileChange($event)"
            required
          />
        </div>
        <div class="file-path-wrapper">
          <input
            class="file-path validate"
            type="text"
            :placeholder="filename"
          />
        </div>
      </div>
      <!-- 이미지 미리보기 관련 내용 추가 -->
      <div v-if="preview" class="input-field col s12">
        <img
          class="_materialboxed"
          width="500"
          id="picture"
          :src="preview"
          alt="이미지 미리보기"
          style="margin-top: 10px"
        />
        <label class="active" for="picture">미리보기</label>
      </div>
      <!-- 기존 업로드 이미지 미리보기 -->
      <div v-else class="input-field col s12">
        <img
          class="_materialboxed"
          width="500"
          id="picture"
          :src="pictureUrl()"
          alt="{item.itemName}"
          style="margin-top: 10px"
          @error="replaceByDefault"
        />
        <label class="active" for="picture">미리보기</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <textarea
          id="description"
          class="materialize-textarea"
          v-model="description"
          style="height: 100px"
          required
        ></textarea>
        <label class="active" for="description">상품설명</label>
      </div>
    </div>
    </table>
    <br />
    <div>
      <router-link
        :to="{ name: 'ItemReadPage', params: { itemId: item.itemId.toString() } }"
        class="waves-effect waves-light btn"
      >취소</router-link>&nbsp;
      <button type="submit" class="waves-effect waves-light btn blue">수정</button>
    </div>
  </form>
  </div>
</template>

<script>
export default {
  name: 'ItemModifyForm',
  props: {
    item: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      itemName: '',
      price: 0,
      description: '',
      file: '',
      filename: '',
      preview: '',
      previewDefault: 'https://picsum.photos/500/300',
    };
  },
  methods: {
    pictureUrl() {
      return `http://localhost:8080/items/display?itemId=${this.item.itemId}&timestamp=${new Date().getTime()}`;
    },
    replaceByDefault(e) {
      e.target.src = this.previewDefault;
      this.filename = '업로드된 파일 없음';
    },
    handleFileChange(e) {
      // 이미지 미리보기 관련 내용 추가
      const fileReader = new FileReader();
      fileReader.readAsDataURL(e.target.files[0]);
      fileReader.onload = () => {
        this.preview = fileReader.result;
      };
      this.file = e.target.files[0];
      //console.log(this.file);
    },
    onSubmit() {
      const { itemName, price, description, file } = this;
      this.$emit('submit', { itemName, price, description, file });
    },
  },
  created() {
    this.itemName = this.item.itemName;
    this.price = this.item.price;
    this.description = this.item.description;
    // 파일 명 가져오기
    const filename = this.item.pictureUrl.split('_').splice(1).join('_');
    this.filename = filename;
  }
};
</script>

<style scoped>
.item {
  margin-top: 10px;
  margin-bottom: 9px;
  font-size: 16px;
  padding-bottom: 9px;
  border-bottom: 1px solid lightgray;
}
</style>

// _study/onnote/react/react-tutorial/8-file-board/src/components/ItemModifyForm.js
import React, { useState, useCallback, useEffect } from 'react';
import { Link } from 'react-router-dom';

function ItemModifyForm({ item, isLoading, onModify }) {
  const [itemName, setItemName] = useState('');
  const [price, setPrice] = useState(0);
  const [description, setDescription] = useState('');
  // 사용자 변경 이미지 파일명
  const [file, setFile] = useState(null);
  // 이미지 미리보기 관련 내용 추가
  const [preview, setPreview] = useState(null);

  // 이미지 표시 URL 생성
  const pictureUrl = (itemId) => {
    return (
      `/items/display?itemId=${itemId}&timestamp=${new Date().getTime()}`
    );
  };

  const handleChangeItemName = useCallback((e) => {
    setItemName(e.target.value);
  }, []);
  const handleChangePrice = useCallback((e) => {
    setPrice(e.target.value);
  }, []);
  const handleChangeDescription = useCallback((e) => {
    setDescription(e.target.value);
  }, []);
  const handleChangeFile = useCallback((e) => {
    // 이미지 미리보기 관련 내용 추가
    const fileReader = new FileReader();
    fileReader.readAsDataURL(e.target.files[0]);
    fileReader.onload = () => {
      setPreview(fileReader.result);
    };
    //console.log(e.target.files[0]);
    setFile(e.target.files[0]);
  }, []);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    onModify(itemName, price, description, file);
  }, [onModify, itemName, price, description, file]);

  useEffect(() => {
    if (item) {
      setItemName(item.itemName);
      setPrice(item.price);
      setDescription(item.description);
      // 파일명 가져오기
      const filename = item.pictureUrl.split('_').splice(1).join('_');
      setFile(filename);
    }
  }, [item]);

  return (
    <div className="container">
      <h3>상품 수정</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && item && (
        <div className="row">
          <form onSubmit={handleSubmit} className="col s12">
            <div className="row">
              <div className="input-field col s5">
                <input type="text" id="itemId" value={item.itemId} disabled />
                <label className="active" htmlFor="itemId">상품번호</label>
              </div>
              <div className="input-field col s7">
                <input type="text" id="price" value={price} onChange={handleChangePrice} />
                <label className="active" htmlFor="price">상품가격 (원)</label>
              </div>
              <div className="input-field col s12">
                <input
                  type="text"
                  id="itemName"
                  value={itemName}
                  onChange={handleChangeItemName}
                  required
                />
                <label className="active" htmlFor="itemName">상품명</label>
              </div>
            </div>
            <div className="row">
              <div className="file-field input-field col s12">
                <div className="btn">
                  <span>파일선택</span>
                  <input type="file" onChange={handleChangeFile} />
                </div>
                <div className="file-path-wrapper">
                  <input className="file-path validate" type="text"
                    placeholder={file} />
                </div>
              </div>
              {/* 이미지 미리보기 관련 내용 추가 */}
              {preview ? (
                <div className="input-field col s12">
                  {/* 수정한 이미지 미리보기 */}
                  <img
                    //className="materialboxed"
                    width="500"
                    id="picture"
                    src={preview}
                    alt="이미지 미리보기"
                    style={{ marginTop: '10px' }}
                  />
                  <label className="active" htmlFor="picture">미리보기</label>
                </div>
              ) : (
                <div className="input-field col s12">
                  {/* 기존 업로드 이미지 */}
                  <img
                    //className="materialboxed"
                    width="500"
                    id="picture"
                    src={pictureUrl(item.itemId)}
                    alt={item.itemName}
                    style={{ marginTop: '10px' }}
                    // 이미지 로딩 에러시 임의의 이미지 출력
                    onError={({ currentTarget }) => {
                      currentTarget.onerror = null;
                      currentTarget.src="https://picsum.photos/500/300";
                    }}
                  />
                  <label className="active" htmlFor="picture">미리보기</label>
                </div>
              )}
            </div>
            <div className="row">
              <div className="input-field col s12">
                <textarea
                  id="description"
                  className="materialize-textarea"
                  value={description}
                  onChange={handleChangeDescription}
                  style={{ height: 100 }}
                  required
                ></textarea>
                <label className="active" htmlFor="description">상품설명</label>
              </div>
            </div>
            <br />
            <Link to={`/read/${item.itemId}`} className="waves-effect waves-light btn">취소</Link>{' '}
            <button type="submit" className="waves-effect waves-light btn blue">완료</button>
          </form>
        </div>
      )}
    </div>
  );
}

export default ItemModifyForm;
