// _study/onnote/react/chap09_실전 프로젝트/21_상품 구매/src/components/useritem/UserItemRead.js
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

import M from 'materialize-css';

// 부모 컴포넌트에서 컴포넌트 속성으로 수신
const UserItemRead = ({ userItem, isLoading }) => {
  // 미리보기 이미지 URL 생성
  const pictureUrl = () => {
    return (
      `/items/display?itemId=${userItem.itemId}&timestamp=${new Date().getTime()}`
    );
  };
  const previewUrl = () => {
    return (
      `/items/preview?itemId=${userItem.itemId}&timestamp=${new Date().getTime()}`
    );
  };

  useEffect(() => {
    M.AutoInit(); // materialboxed 사용
  });

  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '40px' }}>구매상품 상세보기</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && userItem && (
        <div className="row">
          <div className="row">
            <div className="input-field col s5">
              <input type="text" id="userItemId" value={userItem.userItemNo} disabled />
              <label className="active" htmlFor="userItemId">상품번호</label>
            </div>
            <div className="input-field col s7">
              <input type="text" id="price" value={userItem.price} readOnly />
              <label className="active" htmlFor="price">상품가격 (원)</label>
            </div>
            <div className="input-field col s12">
              <input
                type="text"
                id="userItemName"
                value={userItem.itemName}
                readOnly
              />
              <label className="active" htmlFor="userItemName">상품명</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <img
                className="materialboxed"
                width="500"
                id="picture"
                src={pictureUrl()}
                alt={userItem.itemName}
                style={{ marginTop: '10px' }}
                // 이미지 로딩 에러시 임의의 이미지 출력
                onError={({ currentTarget }) => {
                  currentTarget.onerror = null;
                  currentTarget.src="https://picsum.photos/500/300";
                }}
              />
              <label className="active" htmlFor="picture">상품파일</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <img
                className="materialboxed"
                width="500"
                id="picture"
                src={previewUrl()}
                alt={userItem.itemName}
                style={{ marginTop: '10px' }}
                // 이미지 로딩 에러시 임의의 이미지 출력
                onError={({ currentTarget }) => {
                  currentTarget.onerror = null;
                  currentTarget.src="https://picsum.photos/500/300";
                }}
              />
              <label className="active" htmlFor="picture">미리보기파일</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <textarea
                id="description"
                className="materialize-textarea"
                value={userItem.description}
                style={{ height: 100 }}
                readOnly
              ></textarea>
              <label className="active" htmlFor="description">상품설명</label>
            </div>
          </div>
          <br />
          <Link to="/useritem" className="waves-effect waves-light btn">
            상품 목록
          </Link>
        </div>
      )}
    </div>
  );
};

export default UserItemRead;

// _study/onnote/vue_js/chap07_실전 프로젝트/21_상품 구매/src/components/useritem/UserItemRead.vue
<template>
  <div>
    <table>
      <tr>
        <td>상품번호</td>
        <td><input type="text" :value="userItem.userItemNo" readonly /></td>
      </tr>
      <tr>
        <td>상품명</td>
        <td><input type="text" :value="userItem.itemName" readonly /></td>
      </tr>
      <tr>
        <td>상품가격</td>
        <td><input type="text" :value="userItem.price" readonly />원</td>
      </tr>
      <tr>
        <td>상품파일</td>
        <td><img v-bind:src="pictureUrl()" width="170" /></td>
      </tr>
      <!--<tr>
        <td>미리보기파일</td>
        <td><img v-bind:src="previewUrl()" width="170" /></td>
      </tr>-->
      <tr>
        <td>상품설명</td>
        <td><textarea :value="userItem.content" cols="23" rows="5" readonly></textarea></td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'UserItemRead',
  props: {
    userItem: {
      type: Object,
      required: true,
    },
  },
  methods: {
    pictureUrl() {
      return `http://localhost:8080/items/display?itemId=${this.userItem.itemId}&timestamp=${new Date().getTime()}`;
    },
    /*previewUrl() {
      return `http://localhost:8080/items/preview?itemId=${this.userItem.itemId}&timestamp=${new Date().getTime()}`;
    },*/
  },
};
</script>
