// _study/onnote/react/react-tutorial/9-image-shop/src/components/common/MenuBar.js
import React from 'react';
import { Link } from 'react-router-dom';

const MenuBar = () => {
  return (
    <div>
      <table>
        <tbody>
          <tr>
            <td style={{ width: 120, textAlign: 'center' }}><Link to="/">홈</Link></td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default MenuBar;

// _study/onnote/vue_js/chap07_실전 프로젝트/13_코드그룹 관리/src/components/common/MenuBar.vue
<template>
  <div align="center">
    <table>
      <tr>
        <template v-if="isAuthorized">
          <template v-if="isAdmin">
            <td width="6-"><router-link :to="{ name: 'Home' }">홈</router-link></td>
            <td width="120"><router-link :to="{ name: 'CodeGroupListPage' }">코드그룹관리</router-link></td>
          </template>
          <template v-else>
            <td width="60"><router-link :to="{ name: 'Home' }">홈</router-link></td>
          </template>
        </template>
        <template v-else>
          <td width="60"><router-link :to="{ name: 'Home' }">홈</router-link></td>
        </template>
      </tr>
    </table>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  name: 'MenuBar',
  computed: {
    ...mapGetters(['isAuthorized', 'isAdmin']),
  },
};
</script>
