// _study/onnote/react/chap09_실전 프로젝트/10_로그인 여부 확인/src/components/common/MainHeader.js
import React from 'react';
import { Link } from 'react-router-dom';

const MainHeader = ({ isAuthorized, userInfo }) => {
  return (
    <div align="right">
      {isAuthorized && userInfo && (
        <div><span>{userInfo.userName}님 환영합니다.</span></div>
      )}
      {!isAuthorized && !userInfo && (
        <Link to='/signin'>로그인</Link>
      )}
    </div>
  );
}

export default MainHeader;

// _study/onnote/vue_js/chap07_실전 프로젝트/12_로그아웃 처리/src/components/common/MainHeader.vue
<template>
  <div align="right">
    <div v-if="isAuthorized">
      <span>{{ userInfo.userName }}님 환영합니다.</span>&nbsp;
      <button @click="onClickSignout">로그아웃</button>
    </div>
    <div v-else>
      <router-link :to="{ name: 'Signin' }">로그인</router-link>
    </div>
  </div>
</template>

<script>
import { mapState, mapGetters, mapActions } from 'vuex';

export default {
  name: 'MainHeader',
  computed: {
    ...mapState(['userInfo']),
    ...mapGetters(['isAuthorized', 'isAdmin']),
  },
  methods: {
    ...mapActions(['signout']),
    // 로그아웃 처리 메서드
    onClickSignout() {
      this.signout();
      alert('로그아웃 되었습니다.');
      this.$router.push({ name: 'Home' });
    },
  }
};
</script>
