// _study/onnote/react/chap08_파일 게시판/9_상품 목록/src/components/ItemList.js
import React from 'react';
import { Link } from 'react-router-dom';

function ItemList({ items, isLoading }) {
  return (
    <div className="container">
      <h3>상품 목록</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && items && (
        <>
          <table>
            <thead>
              <tr>
                <th style={{ width: 80, textAlign: 'center' }}>상품아이디</th>
                <th style={{ width: 320, textAlign: 'center' }}>상품명</th>
                <th style={{ width: 100, textAlign: 'center' }}>상품가격</th>
              </tr>
            </thead>
            <tbody>
              {!items.length && (
                <tr>
                  <td></td>
                  <td colSpan={4}>List is empty.</td>
                </tr>
              )}
              {!!items.length &&
                items.map((item) => (
                  <tr key={item.itemId}>
                    <td style={{ textAlign: 'center' }}>{item.itemId}</td>
                    <td style={{ textAlign: 'left', paddingLeft: 50 }}>
                      <Link to={`/read/${item.itemId}`}>{item.itemName}</Link>
                    </td>
                    <td style={{ textAlign: 'right', paddingRight: 40 }}>
                      {item.price}원
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
          <br />
          <Link to="/create" className="waves-effect waves-light btn blue">
            새로운 상품 등록
          </Link>
        </>
      )}
    </div>
  );
}

export default ItemList;

// _study/onnote/vue_js/vue-tutorial/6-file-board-materialize/src/components/ItemList.vue
<template>
  <div>
    <table>
      <tr>
        <th width="80" style="text-align: center">상품아이디</th>
        <th width="320" style="text-align: center">상품명</th>
        <th width="100" style="text-align: center">상품가격</th>
      </tr>
      <tr v-if="!items || (Array.isArray(items) && items.length === 0)">
        <td colspan="3">List is empty.</td>
      </tr>
      <tr v-else v-for="item in items" :key="item.itemId">
        <td style="text-align: center">{{ item.itemId }}</td>
        <td style="text-align: left; padding-left: 50px;">
          <router-link
            :to="{ name: 'ItemReadPage', params: { itemId: item.itemId.toString() } }"
          >{{ item.itemName }}</router-link>
        </td>
        <td style="text-align: right; padding-right: 40px;">{{ item.price }}원</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'ItemList',
  props: {
    items: {
      type: Array,
    },
  },
};
</script>
