// _study/onnote/react/react-tutorial/8-file-board/src/components/ItemRead.js
import React from 'react';
import { Link } from 'react-router-dom';

function ItemRead({ itemId, item, isLoading }) {
  // 이미지 표시 URL 생성
  const pictureUrl = () => {
    return (
      `/items/display?itemId=${itemId}&timestamp=${new Date().getTime()}`
    );
  };

  return (
    <div className="container">
      <h3>상품 상세보기</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && item && (
        <div className="row">
          <div className="row">
            <div className="input-field col s5">
              <input type="text" id="itemId" value={item.itemId} disabled />
              <label className="active" htmlFor="itemId">상품번호</label>
            </div>
            <div className="input-field col s7">
              <input type="text" id="price" value={`${item.price}원`} readOnly />
              <label className="active" htmlFor="price">상품가격</label>
            </div>
            <div className="input-field col s12">
              <input
                type="text"
                id="itemName"
                value={item.itemName}
                readOnly
              />
              <label className="active" htmlFor="itemName">상품명</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <img
                //className="materialboxed"
                width="500"
                id="picture"
                //src="https://picsum.photos/500/300"
                src={pictureUrl()}
                alt={item.itemName}
                style={{ marginTop: '10px' }}
              />
              <label className="active" htmlFor="picture">미리보기</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <textarea
                id="description"
                className="materialize-textarea"
                value={item.description}
                style={{ height: 100 }}
                readOnly
              ></textarea>
              <label className="active" htmlFor="description">상품설명</label>
            </div>
          </div>
          <br />
          <Link to="/" className="waves-effect waves-light btn">
            상품 목록
          </Link>{' '}
          <Link to={`/edit/${itemId}`} className="waves-effect waves-light btn blue">수정</Link>{' '}
          <button className="waves-effect waves-light btn red right">삭제</button>
        </div>
      )}
    </div>
  );
}

export default ItemRead;

// _study/onnote/vue_js/vue-tutorial/6-file-board-materialize/src/components/ItemRead.vue
<template>
  <div class="row">
      <div class="row">
        <div class="input-field col s5">
          <input type="text" id="itemId" :value="item.itemId" disabled>
          <label class="active" for="itemId">상품번호</label>
        </div>
        <div class="input-field col s7">
          <input type="text" id="price" :value="item.price" readonly>
          <label class="active" for="price">상품가격 (원)</label>
        </div>
        <div class="input-field col s12">
          <input type="text" id="itemName" :value="item.itemName" readonly>
          <label class="active" for="itemName">상품명</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <img
            class="materialboxed"
            width="500"
            id="picture"
            :src="pictureUrl()"
            alt="{item.itemName}"
            style="margin-top: 10px"
            @error="replaceByDefault"
          />
          <label class="active" htmlFor="picture">미리보기</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea
            id="description"
            class="materialize-textarea"
            :value="item.description"
            style="height: 100px"
            readonly
          ></textarea>
          <label class="active" for="description">상품설명</label>
        </div>
      </div>
  </div>
</template>

<script>
export default {
  name: 'ItemRead',
  props: {
    item: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      preview: 'https://picsum.photos/500/300',
    };
  },
  methods: {
    pictureUrl() {
      return `http://localhost:8080/items/display?itemId=${this.item.itemId}&timestamp=${new Date().getTime()}`;
    },
    replaceByDefault(e) {
      e.target.src = this.preview;
    },
  },
};
</script>
