// _study/onnote/react/chap09_실전 프로젝트/21_상품 구매/src/components/coin/CoinPayList.js
import React from 'react';

// 부모 컴포넌트에서 컴포넌트 속성으로 수신
const CoinPayList = ({ payCoins, isLoading }) => {
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '30px' }}>구매 내역</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && payCoins && (
        <>
          <table>
            <thead>
              <tr>
                <th style={{ width: 80, textAlign: 'center' }}>번호</th>
                <th style={{ width: 180, textAlign: 'center' }}>상품명</th>
                <th style={{ width: 180, textAlign: 'center' }}>구매금액</th>
                <th style={{ width: 180, textAlign: 'center' }}>구매일시</th>
              </tr>
            </thead>
            <tbody>
              {!payCoins.length && (
                <tr>
                  <td></td>
                  <td colSpan="4">List is empty.</td>
                </tr>
              )}
              {!!payCoins.length && payCoins.map((payCoin) => (
                  <tr key={payCoin.historyNo}>
                    <td style={{ textAlign: 'center' }}>
                      {payCoin.historyNo}
                    </td>
                    <td style={{ textAlign: 'left', paddingLeft: 50 }}>
                      {payCoin.itemName}
                    </td>
                    <td style={{ textAlign: 'right', paddingRight: 50 }}>
                      {payCoin.amount}코인
                    </td>
                    <td style={{ textAlign: 'center' }}>
                      {payCoin.regDate}
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
};

export default CoinPayList;

// _study/onnote/vue_js/chap07_실전 프로젝트/21_상품 구매/src/components/coin/CoinPayList.vue
<template>
  <div>
    <table>
      <tr>
        <th align="center" width="80">번호</th>
        <th align="center" width="180">상품명</th>
        <th align="center" width="120">구매금액</th>
        <th align="center" width="180">구매일시</th>
      </tr>
      <tr v-if="!payCoins || (Array.isArray(payCoins) && payCoins.length === 0)">
        <td colspan="4">List is empty.</td>
      </tr>
      <tr v-else v-for="payCoin in payCoins" :key="payCoin.historyNo">
        <td align="center">{{ payCoin.historyNo }}</td>
        <td align="left">{{ payCoin.itemName }}</td>
        <td align="right">{{ payCoin.amount }}원</td>
        <td align="center">{{ payCoin.regDate }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'CoinPayList',
  props: {
    payCoins: {
      type: Array,
    },
  },
};
</script>

<style scoped>
table {
  border-top: 1px solid lightgray;
  border-collapse: collapse;
}
th, td {
  border-bottom: 1px solid lightgray;
  padding: 10px;
}
</style>
