// _study/onnote/vue_js_3/chap03_Vue_js_3 기본/3-15_Vue 컴포넌트/1-컴포넌트 명명 규칙/src/components/BoardRegisterForm.vue
<template>
  <h3>게시판 등록 폼</h3>
  <table>
    <tr>
      <td>제목</td>
      <td><input type="text"></td>
    </tr>
    <tr>
      <td>작성자</td>
      <td><input type="text"></td>
    </tr>
    <tr>
      <td>내용</td>
      <td><textarea name="content" id="content" cols="23" rows="5"></textarea></td>
    </tr>
  </table>
  <div>
    <button>등록</button>
    <button>취소</button>
  </div>
</template>

<script>
export default {
  // 컴포넌트 이름
  name: 'BoardRegisterForm',
};
</script>

// _study/onnote/react/chap05_CRUD 게시판/4_라우터 정의/src/components/BoardRegisterForm.js
import React from 'react';
import { Link } from 'react-router-dom';

function BoardRegisterForm() {
  return (
    <div align="center">
      <h2>게시판 등록</h2>
      <form>
        <table>
          <tbody>
            <tr>
              <td>제목</td>
              <td>
                <input type="text" />
              </td>
            </tr>
            <tr>
              <td>작성자</td>
              <td>
                <input type="text" />
              </td>
            </tr>
            <tr>
              <td>내용</td>
              <td>
                <textarea rows="5"></textarea>
              </td>
            </tr>
          </tbody>
        </table>

        <div>
          <button type="submit">등록</button>
          <Link to="/">취소</Link>
        </div>
      </form>
    </div>
  );
}

export default BoardRegisterForm;
