// _study/onnote/vue_js/vue-tutorial/5-crud-board/src/components/BoardModifyForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>번호</td>
        <td><input type="text" :value="board.boardNo" disabled /></td>
      </tr>
      <tr>
        <td>등록일시</td>
        <td><input type="text" :value="board.regDate" disabled /></td>
      </tr>
      <tr>
        <td>작성자</td>
        <td><input type="text" :value="board.writer" disabled /></td>
      </tr>
      <tr>
        <td>제목</td>
        <td><input type="text" v-model="title" /></td>
      </tr>
      <tr>
        <td>내용</td>
        <td><textarea v-model="content" cols="23" rows="5"></textarea></td>
      </tr>
    </table>

    <div>
      <button type="submit">수정</button>
      <router-link
        :to="{ name: 'BoardReadPage', params: { boardNo: board.boardNo.toString() } }"
      >취소</router-link>
    </div>
  </form>
</template>

<script>
export default {
  name: 'BoardModifyForm',
  props: {
    board: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      title: '',
      content: '',
    };
  },
  methods: {
    onSubmit() {
      const { title, content } = this;
      this.$emit('submit', { title, content });
    },
  },
  created() {
    this.title = this.board.title;
    this.content = this.board.content;
  },
};
</script>

// _study/onnote/react/chap05_CRUD 게시판/4_라우터 정의/src/components/BoardModifyForm.js
import React from 'react';
import { Link } from 'react-router-dom';

function BoardModifyForm() {
  return (
    <div align="center">
      <h2>게시판 수정</h2>
      <form>
        <table>
          <tbody>
            <tr>
              <td>번호</td>
              <td>
                <input value="100" type="text" disabled />
              </td>
            </tr>
            <tr>
              <td>등록일시</td>
              <td>
                <input value="2022-02-23" type="text" disabled />
              </td>
            </tr>
            <tr>
              <td>작성자</td>
              <td>
                <input type="text" value="홍길동" disabled />
              </td>
            </tr>
            <tr>
              <td>제목</td>
              <td>
                <input type="text" />
              </td>
            </tr>
            <tr>
              <td>내용</td>
              <td>
                <textarea rows="5"></textarea>
              </td>
            </tr>
          </tbody>
        </table>

        <div>
          <button type="submit">수정</button>
          <Link to={'/read/100'}>취소</Link>
        </div>
      </form>
    </div>
  );
}

export default BoardModifyForm;
