// _study/onnote/vue_js_typescript/vue-typescript-tutorial/4-todo-app/src/components/TodoInput.vue
<template>
  <div>
    <input type="text" />
    <button>추가</button>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class TodoInput extends Vue {

}
</script>

<style scoped>
div {
  background-color: Pink;
}
button {
  margin: 5px;
}
</style>

// _study/onnote/react/chap04_Todo 애플리케이션/4_화면 구성/src/components/TodoInput.js
import React from 'react';

import styles from '../Todo.module.css';

const TodoInput = () => {
  return (
    <div className={styles.input}>
      <form>
        <input type="text" placeholder="할 일을 입력하세요" />
        <button type="submit">추가</button>
      </form>
      <h1>TodoInput</h1>
    </div>
  );
};

export default TodoInput;
