// _study/onnote/vue_js_3/chap03_Vue_js_3 기본/3-13_이벤트 처리/2-옵션 API 방식/src/App.vue
<template>
  <h2>Vue 이벤트 처리 (기존 옵션 API 방식)</h2>
  <form v-on:submit.prevent="onSubmit">
    <table>
      <tr>
        <td>사용자 아이디</td>
        <td><input type="text" v-bind:value="userId" v-on:input="userId = $event.target.value" /></td>
      </tr>
      <tr>
        <td>비밀번호</td>
        <td><input type="password" v-bind:value="userPw" v-on:change="userPw = $event.target.value" /></td>
      </tr>
      <tr>
        <td>소개</td>
        <td><textarea v-model="introduction"></textarea></td>
      </tr>
      <tr>
        <td>개발자 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox" />
          <span>handleCheckBox</span>
        </td>
      </tr>
      <tr>
        <td>개발자 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox()" />
          <span>handleCheckBox()</span>
        </td>
      </tr>
      <tr>
        <td>개발자 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox2" />
          <span>handleCheckBox2</span>
        </td>
      </tr>
      <tr>
        <td>개발자 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox2($event)" />
          <span>handleCheckBox2($event)</span>
        </td>
      </tr>
      <tr>
        <td>개발자 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox3('checked!')" />
          <span>handleCheckBox3('checked!')</span>
        </td>
      </tr>
      <tr>
        <td>외국인 여부</td>
        <td>
          <input type="checkbox" v-on:change="handleCheckBox4('checked!', $event)" />
          <span>handleCheckBox4('checked!', $event)</span>
        </td>
      </tr>
      <tr>
        <td>취미</td>
        <td>
          <input type="checkbox" id="chkSports" value="Sports" v-model="hobbyList" />
          <label for="chkSports">Sports</label>
          <input type="checkbox" id="chkMusic" value="Music" v-model="hobbyList" />
          <label for="chkMusic">Music</label>
          <input type="checkbox" id="chkMovie" value="Movie" v-model="hobbyList" />
          <label for="chkMovie">Movie</label>
        </td>
      </tr>
      <tr>
        <td>성별</td>
        <td>
          <input type="radio" id="rdoMale" value="male" v-model="gender" />
          <label for="rdoMale">Male</label>
          <input type="radio" id="rdoFemale" value="female" v-model="gender" />
          <label for="rdoFemale">Female</label>
          <input type="radio" id="rdoNone" value="none" v-model="gender" />
          <label for="rdoNone">None</label>
        </td>
      </tr>
      <tr>
        <td>국적</td>
        <td>
          <select v-model="nationality">
            <option disabled value="">Please select one</option>
            <option value="01">Korea</option>
            <option value="02">Gemany</option>
            <option value="03">Australia</option>
          </select>
        </td>
      </tr>
      <tr>
        <td>소유차량</td>
        <td>
          <select v-model="carList" multiple>
            <option>Benz</option>
            <option>BMW</option>
            <option>Audi</option>
            <option>Volvo</option>
            <option>Saab</option>
          </select>
        </td>
      </tr>
    </table>
    <p><button type="submit">등록</button></p>
  </form>
</template>

<script>
export default {
  data() {
    return {
      userId: '',
      userPw: '',
      introduction: '',
      developer: false,
      foreigner: 'no',
      hobbyList: [],
      gender: 'male',
      nationality: '',
      carList: [],
    };
  },
  methods: {
    // 데이터 값을 출력한다.
    onSubmit() {
      const { userId, userPw, introduction, developer, foreigner, hobbyList, gender, nationality, carList } = this;
      console.log('userId:', userId);
      console.log('userpw:', userPw);
      console.log('introduction:', introduction);
      console.log('developer:', developer);
      console.log('foreigner:', foreigner);
      console.log('hobbyList:', hobbyList);
      console.log('gender:', gender);
      console.log('nationality:', nationality);
      console.log('carList:', carList);
    },
    // 인자없는 메서드
    handleCheckBox() {
      console.log('handleCheckBox');
    },
    // event 인자를 가진 메서드
    handleCheckBox2(event) {
      console.log('handleCheckBox2 event:', event);
    },
    // 메서드 인자를 가진 메서드
    handleCheckBox3(message) {
      console.log('handleCheckBox3 message:', message);
    },
    // 메서드 인자와 event 인자를 가진 메서드
    handleCheckBox4(message, event) {
      console.log('handleCheckBox4 message:', message);
      console.log('handleCheckBox4 event:', event);
    },
  },
};
</script>

// _study/onnote/angular/chap04_앵귤러 기본/6_디렉티브/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  // 데이터 정의
  userId = 'alex';
  userPw = '1234';
  introduction = 'hello';
  developer = true;
  foreigner = 'yes';
  hobbyList = ['Sports', 'Music', 'Movie'];
  gender = 'male';
  nationality = '01';
  cars = ['Volvo', 'Saab', 'Opel'];
  selectedCars = ['Volvo', 'Saab'];

  getNationality() {
    if (this.nationality === '01') {
      return 'Korea';
    } else if (this.nationality === '02') {
      return 'Germany';
    } else if (this.nationality === '03') {
      return 'Australia';
    } else {
      return 'None';
    }
  }
}

<form>
  <table>
    <tr>
      <td>사용자아이디</td>
      <td>{{ userId }}</td>
    </tr>
    <tr>
      <td>비밀번호</td>
      <td><input type="password" [value]="userPw" /></td>
    </tr>
    <tr>
      <td>소개</td>
      <td><textarea rows="5" [value]="introduction"></textarea></td>
    </tr>
    <tr>
      <td>개발자여부</td>
      <td>
        <span *ngIf="developer">개발자</span>
      </td>
    </tr>
    <tr>
      <td>외국인여부</td>
      <td>
        <span *ngIf="foreigner === 'yes'">외국인</span>
      </td>
    </tr>
    <tr>
      <td>취미</td>
      <td>
        <ul>
          <li *ngFor="let hobby of hobbyList">{{ hobby }}</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>성별</td>
      <td>
        <span *ngIf="gender === 'male';else other_content">Male</span>
        <ng-template #other_content>Female</ng-template>
      </td>
    </tr>
    <tr>
      <td>국적</td>
      <td>
        <select [value]="nationality">
          <option disabled value="">Please select one</option>
          <option value="01">Korea</option>
          <option value="02">Germany</option>
          <option value="03">Australia</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>국적</td>
      <td>
        <ng-container [ngSwitch]="nationality">
          <span *ngSwitchCase="'01'">Korea</span>
          <span *ngSwitchCase="'02'">Germany</span>
          <span *ngSwitchCase="'03'">Australia</span>
          <span *ngSwitchDefault>None</span>
        </ng-container>
      </td>
    </tr>
    <tr>
      <td>국적</td>
      <td>
        {{ getNationality() }}
      </td>
    </tr>
    <tr>
      <td>소유차량</td>
      <td>
        <select name="selectedCars" [(ngModel)]="selectedCars" multiple>
          <option *ngFor="let car of cars" [ngValue]="car">{{car}}</option>
        </select>
      </td>
    </tr>
  </table>

  <p>
    <button type="submit">등록</button>
  </p>
</form>
