// _study/onnote/vue_js/vue-tutorial/7-image-shop/src/components/coin/CoinChargeList.vue
<template>
  <div>
    <table>
      <tr>
        <th align="center" width="80">번호</th>
        <th align="center" width="320">충전금액</th>
        <th align="center" width="180">등록일시</th>
      </tr>
      <tr v-if="!chargeCoins || (Array.isArray(chargeCoins) && chargeCoins.length === 0)">
        <td colspan="3">List is empty.</td>
      </tr>
      <tr v-else v-for="chargeCoin in chargeCoins" :key="chargeCoin.historyNo">
        <td align="center">{{ chargeCoin.historyNo }}</td>
        <td align="right" style="padding-right: 120px">{{ chargeCoin.amount }}코인</td>
        <td align="center">{{ chargeCoin.regDate }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'CoinChargeList',
  props: {
    chargeCoins: {
      type: Array,
    },
  },
};
</script>

<style scoped>
table {
  border-top: 1px solid lightgray;
  border-collapse: collapse;
}
th, td {
  border-bottom: 1px solid lightgray;
  padding: 10px;
}
</style>

// _study/onnote/react/chap09_실전 프로젝트/20_코인 충전/src/components/coin/CoinChargeList.js
import React from 'react';

// 부모 컴포넌트에서 컴포넌트 속성으로 수신
const CoinChargeList = ({ chargeCoins, isLoading }) => {
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '30px' }}>충전 내역</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && chargeCoins && (
        <>
          <table>
            <thead>
              <tr>
                <th style={{ width: 80, textAlign: 'center' }}>번호</th>
                <th style={{ width: 180, textAlign: 'center' }}>충전내역</th>
                <th style={{ width: 100, textAlign: 'center' }}>충전일시</th>
              </tr>
            </thead>
            <tbody>
              {!chargeCoins.length && (
                <tr>
                  <td></td>
                  <td colSpan="3">List is empty.</td>
                </tr>
              )}
              {!!chargeCoins.length && chargeCoins.map((chargeCoin) => (
                  <tr key={chargeCoin.historyNo}>
                    <td style={{ textAlign: 'center' }}>
                      {chargeCoin.historyNo}
                    </td>
                    <td style={{ textAlign: 'right', paddingRight: 80 }}>
                      {chargeCoin.amount}코인
                    </td>
                    <td style={{ textAlign: 'center' }}>
                      {chargeCoin.regDate}
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </>
      )}
    </div>
  );
};

export default CoinChargeList;
