// _study/onnote/react/chap09_실전 프로젝트/14_코드 관리/src/components/common/MenuBar.js
import React from 'react';
import { Link } from 'react-router-dom';

// 애플리케이션 메뉴바 화면 표시
const MenuBar = ({ isAuthorized, isAdmin }) => {
  return (
    <div>
      <table>
        <tbody>
          <tr>
            {/* 로그인한 사용자이고 관리자 */}
            {isAuthorized && isAdmin && (
              <>
                <td style={{ width: 120, textAlign: 'center' }}><Link to="/">홈</Link></td>
                <td style={{ width: 120, textAlign: 'center' }}><Link to="/codegroup">코드그룹관리</Link></td>
                <td style={{ width: 120, textAlign: 'center' }}><Link to="/codedetail">코드관리</Link></td>
              </>
            )}
            {/* 로그인한 사용자이고 관리자가 아님 */}
            {isAuthorized && !isAdmin && (
              <td style={{ width: 120, textAlign: 'center' }}><Link to="/">홈</Link></td>
            )}
            {/* 로그인하지 않은 사용자 */}
            {!isAuthorized && (
              <td style={{ width: 120, textAlign: 'center' }}><Link to="/">홈</Link></td>
            )}
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default MenuBar;

// _study/onnote/vue_js/chap07_실전 프로젝트/14_코드 관리/src/components/common/MenuBar.vue
<template>
  <div align="center">
    <table>
      <tr>
        <template v-if="isAuthorized">
          <template v-if="isAdmin">
            <td width="60"><router-link :to="{ name: 'Home' }">홈</router-link></td>
            <td width="130"><router-link :to="{ name: 'CodeGroupListPage' }">코드그룹관리</router-link></td>
            <td width="100"><router-link :to="{ name: 'CodeDetailListPage' }">코드관리</router-link></td>
          </template>
          <template v-else>
            <td width="60"><router-link :to="{ name: 'Home' }">홈</router-link></td>
          </template>
        </template>
        <template v-else>
          <td width="60"><router-link :to="{ name: 'Home' }">홈</router-link></td>
        </template>
      </tr>
    </table>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  name: 'MenuBar',
  computed: {
    ...mapGetters(['isAuthorized', 'isAdmin']),
  },
};
</script>
