// _study/onnote/react/react-tutorial/9-image-shop/src/components/auth/SignInForm.js
import React from 'react';

// 로그인 폼 구성
const SignInForm = () => {
  return (
    <div className="container">
      <h3 className="center">로그인</h3>
      <br />
      <form>
        <div className="row">
          <div className="col s6 offset-s3">
            <div>
              <div>아이디</div>
              <div>
                <input type="text" />
              </div>
            </div>
            <div>
              <div>비밀번호</div>
              <div>
                <input type="password" />
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col s12">
            <div className="center">
              <button type="submit" className="waves-effect waves-light btn">로그인</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  );
}

export default SignInForm;

// _study/onnote/vue_js/chap07_실전 프로젝트/6_로그인 화면/src/components/auth/SigninForm.vue
<template>
  <form @submit.prevent="submit">
    <table>
      <tr>
        <td>아이디</td>
        <td><input type="text" v-model="userId" /></td>
      </tr>
      <tr>
        <td>비밀번호</td>
        <td><input type="password" v-model="password" /></td>
      </tr>
      <tr>
        <td colspan="2" align="center">
          <button type="submit">로그인</button>
        </td>
      </tr>
    </table>
  </form>
</template>

<script>
export default {
  name: 'SigninForm',
  data() {
    return {
      userId: '',
      password: '',
    };
  },
  methods: {
    submit() {
      const { userId, password } = this;
      this.$emit('submit', { userId, password });
    },
  },
};
</script>
