// _study/onnote/react_typescript/chap06_CRUD 게시판/7_게시글 상세보기/src/components/BoardRead.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { Board } from '../App';
import styles from '../Board.module.css';

interface Props {
  readonly boardNo: string;
  readonly board?: Board;
  readonly isLoading: boolean;
}

function BoardRead({ boardNo, board, isLoading }: Props) {
  return (
    <div className={styles.centered}>
      <h2>게시판 상세보기</h2>
      {isLoading && 'Loading...'}
      {!isLoading && board && (
        <>
          <table>
            <tbody>
              <tr>
                <td>번호</td>
                <td><input type="text" value={board.boardNo} readOnly /></td>
              </tr>
              <tr>
                <td>등록일시</td>
                <td><input type="text" value={board.regDate} readOnly /></td>
              </tr>
              <tr>
                <td>작성자</td>
                <td><input type="text" value={board.writer} readOnly /></td>
              </tr>
              <tr>
                <td>제목</td>
                <td><input type="text" value={board.title} readOnly /></td>
              </tr>
              <tr>
                <td>내용</td>
                <td><textarea value={board.content} readOnly></textarea></td>
              </tr>
            </tbody>
          </table>

          <div className={styles.align_centered}>
            <Link to={`/edit/${boardNo}`}>편집</Link>
            <button>삭제</button>
            <Link to="/">목록</Link>
          </div>
        </>
      )}
    </div>
  );
}

export default BoardRead;

// _study/onnote/vue_js/chap07_실전 프로젝트/17_회원 게시판/src/components/board/BoardRead.vue
<template>
  <div>
    <table>
      <tr>
        <td>번호</td>
        <td><input type="text" :value="board.boardNo" readonly /></td>
      </tr>
      <tr>
        <td>등록일시</td>
        <td><input type="text" :value="board.regDate" readonly /></td>
      </tr>
      <tr>
        <td>작성자</td>
        <td><input type="text" :value="board.writer" readonly /></td>
      </tr>
      <tr>
        <td>제목</td>
        <td><input type="text" :value="board.title" readonly /></td>
      </tr>
      <tr>
        <td>내용</td>
        <td><textarea :value="board.content" cols="23" rows="5" readonly></textarea></td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'BoardRead',
  props: {
    board: {
      type: Object,
      required: true,
    },
  },
};
</script>
