// _study/onnote/react/chap09_실전 프로젝트/14_코드 관리/src/components/codedetail/CodeDetailList.js
import React from 'react';
import { Link } from 'react-router-dom';

const CodeDetailList = ({ codeDetails, isLoading }) => {
  // 코드그룹 목록 화면 표시
  return (
    <div className="container">
      <h3 className="center" style={{ marginBottom: '30px' }}>코드 목록</h3>
      {isLoading && (
        <div className="progress">
          <div className="indeterminate"></div>
        </div>
      )}
      {!isLoading && codeDetails && (
        <>
          <table>
            <thead>
              <tr>
                <th style={{ width: 160, textAlign: 'center' }}>코드코드</th>
                <th style={{ width: 160, textAlign: 'center' }}>코드값</th>
                <th style={{ width: 160, textAlign: 'center' }}>코드명</th>
                <th style={{ width: 160, textAlign: 'center' }}>정렬순서</th>
                <th style={{ width: 180, textAlign: 'center' }}>등록일시</th>
              </tr>
            </thead>
            <tbody>
              {!codeDetails.length && (
                <tr>
                  <td></td>
                  <td colSpan="5">List is empty.</td>
                </tr>
              )}
              {!!codeDetails.length && codeDetails.map((codeDetail) => (
                <tr key={`${codeDetail.groupCode}${codeDetail.codeValue}`}>
                  <td style={{ textAlign: 'center' }}>{codeDetail.groupCode}</td>
                  <td style={{ textAlign: 'center' }}>{codeDetail.codeValue}</td>
                  <td style={{ textAlign: 'center'}}>
                    <Link to={`/codedetail/read/${codeDetail.groupCode}/${codeDetail.codeValue}`}>{codeDetail.codeName}</Link>
                  </td>
                  <td style={{ textAlign: 'center'}}>{codeDetail.sortSeq}</td>
                  <td style={{ textAlign: 'center'}}>{codeDetail.regDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <br />
          <Link to="/codedetail/create" className="waves-effect waves-light btn blue">
            새로운 코드 등록
          </Link>
        </>
      )}
    </div>
  );
};

export default CodeDetailList;

// _study/onnote/vue_js/chap07_실전 프로젝트/14_코드 관리/src/components/codedetail/CodeDetailList.vue
<template>
  <div>
    <table>
      <tr>
        <th align="center" width="160">그룹코드</th>
        <th align="center" width="160">코드값</th>
        <th align="center" width="180">코드명</th>
        <th align="center" width="160">정렬순서</th>
        <th align="center" width="160">등록일시</th>
      </tr>
      <tr v-if="!codeDetails || (Array.isArray(codeDetails) && codeDetails.length === 0)">
        <td colspan="5">List is empty.</td>
      </tr>
      <tr v-else v-for="codeDetail in codeDetails" :key="`${codeDetail.groupCode}=${codeDetail.codeValue}`">
        <td align="center">{{ codeDetail.groupCode }}</td>
        <td align="center">{{ codeDetail.codeValue }}</td>
        <td align="left"><router-link :to="{ name: 'CodeDetailReadPage', params: { groupCode: codeDetail.groupCode, codeValue: codeDetail.codeValue } }">{{ codeDetail.codeName }}</router-link></td>
        <td align="center">{{ codeDetail.sortSeq }}</td>
        <td align="center">{{ codeDetail.regDate }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: 'CodeDetailList',
  props: {
    codeDetails: {
      type: Array,
    },
  },
};
</script>

<style scoped>
table {
  border-top: 1px solid lightgray;
  border-collapse: collapse;
}
th, td {
  border-bottom: 1px solid lightgray;
  padding: 10px;
}
</style>
