// _study/onnote/react/chap08_파일 게시판/7_상품 등록/src/components/ItemRegisterForm.js
import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';

function ItemRegisterForm({ onRegister }) {
  const [itemName, setItemName] = useState('');
  const [price, setPrice] = useState(0);
  const [description, setDescription] = useState('');
  const [file, setFile] = useState(null);

  const handleChangeItemName = useCallback((e) => {
    setItemName(e.target.value);
  }, []);
  const handleChangePrice = useCallback((e) => {
    setPrice(e.target.value);
  }, []);
  const handleChangeDescription = useCallback((e) => {
    setDescription(e.target.value);
  }, []);
  const handleChangeFile = useCallback((e) => {
    console.log(e.target.files[0]);
    setFile(e.target.files[0]);
  }, []);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    onRegister(itemName, price, description, file);
  }, [onRegister, itemName, price, description, file]);

  return (
    <div className="container">
      <h3>새로운 상품 등록</h3>
      <div className="row">
        <form onSubmit={handleSubmit} className="col s12">
          <div className="row">
          <div className="input-field col s12">
              <input
                type="text"
                id="itemName"
                value={itemName}
                required
              />
              <label className="active" htmlFor="itemName">상품명</label>
            </div>
            <div className="input-field col s12">
              <input type="text" id="price" value={price} onChange={handleChangePrice} />원
              <label className="active" htmlFor="price">상품가격</label>
            </div>
          </div>
          <div className="row">
            <div className="file-field input-field col s12">
              <div className="btn">
                <span>파일선택</span>
                <input type="file" onChange={handleChangeFile} />
              </div>
              <div className="file-path-wrapper">
                <input className="file-path validate" type="text"  placeholder="선택된 파일 없음" />
              </div>
            </div>
            {/*<div className="input-field col s12">
              <img
                //className="materialboxed"
                width="500"
                id="picture"
                src="https://picsum.photos/500/300"
                alt="풍경사진"
                style={{ marginTop: '10px' }}
              />
              <label className="active" htmlFor="picture">미리보기</label>
            </div>*/}
          </div>
          <div className="row">
            <div className="input-field col s12">
              <textarea
                id="description"
                className="materialize-textarea"
                value={description}
                onChange={handleChangeDescription}
                style={{ height: 100 }}
                required
              ></textarea>
              <label className="active" htmlFor="description">상품설명</label>
            </div>
          </div>
          <br />
          <Link to="/" className="waves-effect waves-light btn">취소</Link>{' '}
          <button type="submit" className="waves-effect waves-light btn blue">등록</button>
        </form>
      </div>
    </div>
  );
}

export default ItemRegisterForm;

// _study/onnote/vue_js/chap06_파일 게시판/6_파일 업로드/src/components/ItemRegisterForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>상품명</td>
        <td><input type="text" v-model="itemName" /></td>
      </tr>
      <tr>
        <td>상품가격</td>
        <td><input type="text" v-model="price" />원</td>
      </tr>
      <tr>
        <td>상품파일</td>
        <td><input type="file" @change="handleFileChange($event)" style="width: 180px" /></td>
      </tr>
      <tr>
        <td>상품설명</td>
        <td><textarea v-model="description" cols="23" rows="5"></textarea></td>
      </tr>
    </table>

    <div>
      <button type="submit">등록</button>
      <router-link :to="{ name: 'ItemListPage' }">취소</router-link>
    </div>
  </form>
</template>

<script>
export default {
  name: 'ItemRegisterForm',
  data() {
    return {
      itemName: '',
      price: '',
      description: '',
      file: '',
    }
  },
  methods: {
    handleFileChange(e) {
      this.file = e.target.files[0];
      console.log(this.file);
    },
    onSubmit() {
      const { itemName, price, description, file } = this;
      this.$emit('submit', { itemName, price, description, file });
    },
  },
};
</script>
