// _study/onnote/vue_js/chap05_CRUD 게시판/6_게시글 등록/src/components/BoardRegisterForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>제목</td>
        <td><input type="text" v-model="title" /></td>
      </tr>
      <tr>
        <td>작성자</td>
        <td><input type="text" v-model="writer" /></td>
      </tr>
      <tr>
        <td>내용</td>
        <td><textarea v-model="content" rows="5"></textarea></td>
      </tr>
    </table>
    <div>
      <button type="submit">등록</button>
      <router-link :to="{ name: 'BoardListPage' }">취소</router-link>
    </div>
  </form>
</template>

<script>
export default {
  name: 'BoardRegisterForm',
  data() {
    return {
      title: '',
      content: '',
      writer: '',
    };
  },
  methods: {
    onSubmit() {
      const { title, content, writer } = this;
      this.$emit('submit', { title, content, writer });
    },
  },
};
</script>

// _study/onnote/react_typescript/chap06_CRUD 게시판/4-라우터 정의/src/components/BoardRegisterForm.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import styles from '../Board.module.css';

function BoardRegisterForm() {
  return (
    <div className={styles.centered}>
      <h2>게시판 등록</h2>
      <form>
        <table>
          <tbody>
            <tr>
              <td>제목</td>
              <td><input type="text" /></td>
            </tr>
            <tr>
              <td>작성자</td>
              <td><input type="text" /></td>
            </tr>
            <tr>
              <td>내용</td>
              <td><textarea rows={5}></textarea></td>
            </tr>
          </tbody>
        </table>

        <div className={styles.align_centerd}>
          <button type="submit">등록</button>
          <Link to="/">취소</Link>
        </div>
      </form>
    </div>
  );
}

export default BoardRegisterForm;
