// _study/onnote/vue_js_3/chap03_Vue_js_3 기본/3-18_이벤트 전달/1-컴포지션 API 방식/src/components/ItemMain.vue
<template>
  <ul>
    <li v-for="(item, index) in items" v-bind:key="item.name">
      <!-- 이벤트 수신 및 처리 -->
      <item-input
        v-bind:item="item"
        v-bind:item-index="index"
        v-on:change-price="handleChangePrice"
      ></item-input>
    </li>
  </ul>
  <hr />
  <item-list></item-list>
</template>

<script>
import { inject } from 'vue';
import ItemList from './ItemList.vue';
import ItemInput from './ItemInput.vue';

export default {
  name: 'ItemMain',
  components: {
    ItemList,
    ItemInput,
  },
  setup() {
    const items = inject('items');
    // TODO: changePrice가 undefined인 이유를 알아보자.
    const changePrice = inject('changePrice');
    console.log(changePrice);
    // change-price 이벤트 처리 메서드
    const handleChangePrice = (newPrice, index) => {
      changePrice(newPrice, index);
    };

    return {
      items,
      handleChangePrice, // 메서드 변수 반환
    };
  },
};
</script>

// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/3_props를 통한 이벤트 처리 함수 전달/src/components/ItemMain.js
import React, { useState } from 'react';
import ItemInput from './ItemInput';
import ItemList from './ItemList';
import ItemTotal from './ItemTotal';

const ItemMain = () => {
  const itemDataArray = [
    {
      name: 'CPU',
      price: 462984,
      quantity: 1,
    },
    {
      name: '메인보드',
      price: 112053,
      quantity: 1,
    },
    {
      name: '메모리',
      price: 79608,
      quantity: 2,
    },
  ];

  const [items, setItems] = useState(itemDataArray);

  // 이벤트 처리 함수 정의
  const onChangePrice = (name, price) => {
    console.log('onChangePrice name:', name, 'price:', price);
    setItems((items) => {
      return items.map((item) => {
        return item.name === name ? { ...item, price: price } : item;
      });
    });
  };

  return (
    <div>
      {/* onChangePrice 속성(props) 값 지정 */}
      <ItemInput items={items} onChangePrice={onChangePrice} />
      <hr />
      <ItemList items={items} />
      <ItemTotal items={items} />
    </div>
  );
};

export default ItemMain;
