// _study/onnote/react/chap05_CRUD 게시판/4_라우터 정의/src/components/BoardRegisterForm.js
import React from 'react';
import { Link } from 'react-router-dom';

function BoardRegisterForm() {
  return (
    <div align="center">
      <h2>게시판 등록</h2>
      <form>
        <table>
          <tbody>
            <tr>
              <td>제목</td>
              <td>
                <input type="text" />
              </td>
            </tr>
            <tr>
              <td>작성자</td>
              <td>
                <input type="text" />
              </td>
            </tr>
            <tr>
              <td>내용</td>
              <td>
                <textarea rows="5"></textarea>
              </td>
            </tr>
          </tbody>
        </table>

        <div>
          <button type="submit">등록</button>
          <Link to="/">취소</Link>
        </div>
      </form>
    </div>
  );
}

export default BoardRegisterForm;

// _study/onnote/vue_js_typescript/chap06_CRUD 게시판/6_게시글 등록/src/components/BoardRegisterForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <table>
      <tr>
        <td>제목</td>
        <td><input type="text" v-model="title" /></td>
      </tr>
      <tr>
        <td>작성자</td>
        <td><input type="text" v-model="writer" /></td>
      </tr>
      <tr>
        <td>내용</td>
        <td><textarea v-model="content" rows="5"></textarea></td>
      </tr>
    </table>
    <div>
      <button type="submit">등록</button>
      <router-link :to="{ name: 'BoardListPage' }">취소</router-link>
    </div>
  </form>
</template>

<script lang="ts">
import { Component, Vue, Emit } from 'vue-property-decorator';

@Component
export default class BoardRegisterForm extends Vue {
  title: string = '';
  content: string = '';
  writer: string = '';

  @Emit('submit')
  onSubmit() {
    const { title, content, writer } = this;

    return {
      title,
      content,
      writer,
    };
  }
}
</script>
