// _study/onnote/vue_js_3/chap03_Vue_js_3 기본/3-18_이벤트 전달/1-컴포지션 API 방식/src/components/ItemList.vue
<template>
  <ul>
    <li v-for="item in items" v-bind:key="item.name">
      {{ item.name }}: {{ item.price }} x {{ item.quantity }} = {{ item.price * item.quantity }}원
    </li>
  </ul>
  <p>합계: {{ totalPrice }}원</p>
</template>

<script>
import { computed, inject } from 'vue';

export default {
  name: 'ItemList',
  setup() {
    const items = inject('items');

    const totalPrice = computed(() => {
      return items.value.reduce(function (sum, item) {
        return sum + item.price * item.quantity;
      }, 0);
    });

    return {
      items,
      totalPrice,
    };
  },
};
</script>

// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/2_컴포넌트 통신/1-src/components/ItemList.js
import React from 'react';
import Item from './Item';

const ItemList = ({ items, totalPrice }) => {
  return (
    <div>
      <ul>
        {/* item 속성(props) 값 지정 */}
        {items.map((item) => {
          return <Item key={item.name} item={item} />;
        })}
      </ul>
      <p>합계: {totalPrice}원</p>
    </div>
  );
};

export default ItemList;
