// _study/onnote/vue_js/chap03_Vue_js 기본/3-17_싱글 파일 컴포넌트/src/components/ItemList.vue
<template>
  <div>
    <ul>
      <li v-for="item in items" v-bind:key="item.name">
        {{ item.name }}: {{ item.price }} x {{ item.quantity }} = {{ item.price * item.quantity }}원
      </li>
    </ul>
    <p>합계: {{ totalPrice }}원</p>
  </div>
</template>

<script>
export default {
  name: 'item-list',
  props: ['items'],
  computed: {
    totalPrice() {
      return this.items.reduce((sum, item) => {
        return sum + item.price * item.quantity;
      }, 0);
    }
  }
};
</script>

// _study/onnote/react/chap03_React/3-06_컴포넌트 속성/2_컴포넌트 통신/1-src/components/ItemList.js
import React from 'react';
import Item from './Item';

const ItemList = ({ items, totalPrice }) => {
  return (
    <div>
      <ul>
        {/* item 속성(props) 값 지정 */}
        {items.map((item) => {
          return <Item key={item.name} item={item} />;
        })}
      </ul>
      <p>합계: {totalPrice}원</p>
    </div>
  );
};

export default ItemList;
